### ISSUE TITLE
Picture/Webcam support

### ISSUE THREAD

**Issue by revol** [mpod/mPage#1]
It would be nice if you can add pictures captured by webcams (ex.: url to jpg) to the pages.
maybe with configurable refreshtimes and size of the pictures

example:
![mpgaewebcam](https://f.cloud.github.com/assets/2205437/682384/1b0970dc-d9c6-11e2-89d6-c0b21ab188ff.jpg)

have a nice day

ps: great addon :+1:

**Comment by mpod** [comment]
I'm actually against pictures on the page, but lets analyze your idea a little bit more. Please, can you send me a link of the web cam site which you used? Thank you.

**Comment by revol** [comment]
i used a local jpg (its a photshopped image ^^)...

i took over this idea from the igoogle dashboard webcam addon.

you can use this jpg for testing:
http://lamp01.dortmund.de/webcams/dortmunder_u/current.jpg

**Comment by mpod** [comment]
Yes, it is time to introduce new kinds of widgets. Your idea will definitely end up in new version. But, it is hard to say when this new version will be released. For next six months I only plan to fix bugs.

The issue stays open.

**Comment by mpod** [comment]
It looks like it is not gonna happen. I'm closing the issue.
