### ISSUE TITLE
Favicon for tabs and sidebar

### ISSUE THREAD

**Issue by Wombat2018** [mpod/mPage#10]
![Unbenannt-3](https://user-images.githubusercontent.com/45123672/55112570-2d543a80-50dd-11e9-84ae-7033dec97235.png)

Hi,

it would be nice to have the orange symbol as a favicon, so there would not be the standard icon for websites without favicons in the bookmark sidebar and no one in the tabs. Here is a screenshot to show the problem.

**Comment by mpod** [comment]
Yes, you are right. It has been added.
