### ISSUE TITLE
Add notification

### ISSUE THREAD

**Issue by Crandel** [mpod/mPage#15]
Hello, 
I trying to use this add-on. It's looks nice but I'm missing a notification count in icon of add-on. Can you add it? Others add-ons has this feature, so I hope this will not be hard to do.
P.S. Notification on pages also would be great

**Comment by mpod** [comment]
I don't understand what do you mean by notification count. Can you give me an example (screenshot maybe) from another add-on? Or try with taking a screenshot of mPage and drawing on it? Thanks!

**Comment by Crandel** [comment]
Something like [this](https://addons.cdn.mozilla.net/user-media/previews/full/185/185751.png?modified=1573849751)

**Comment by mpod** [comment]
Ok, I tried it. As I can see addon adds a counter of unread articles.
Well, I'm not going add such counter to mPage. It would be a big work to add it. But bigger issue is that such feature doesn't fit into mPage. The thing is that I would not use it. When that number gets bigger (more than 20?), it just becomes unimportant, nobody cares about it. I see mPage more like light alternative to the usual feed readers. Tracking of visited links doesn't fit here.

However, today I've implemented notification that there are some feeds available on current tab. It will be released shortly.

**Comment by ruink33per** [comment]
@mpod Thanks for your work and the notification feature, mpage is perfect. Could make the notification optional?

**Comment by mpod** [comment]
It can be done. Will do it in next release, shortly.

**Comment by mpod** [comment]
It's added and new version has been released.
