### ISSUE TITLE
Column Widths Issue Due to Long Article Title

### ISSUE THREAD

**Issue by noteasybeingreen** [mpod/mPage#16]
Firefox 77.0.1
Windows 7 & Windows 10
Screenshot attached with feeds hidden - long-width article title in white

I love the mPage add-on (I use 3-column width) but once in a blue moon an article title in one rss feed will be very long without spacing which throws column widths off.  Is it possible to have auto column widths/column max-width/percentage width options such as 33%-33%-33%/editable width boundaries/etc. to prevent this "visual defect" from occurring? I looked into editing css but not sure how to make permanent for an add-on.

Either way, thanks for the great work. Hope this finds you and your family well. Enjoy the rest of your day.

![20200619-mpage-3col-widths](https://user-images.githubusercontent.com/67170068/85179246-806c5d00-b24e-11ea-99a5-dec4e2eda06f.jpg)

**Comment by mpod** [comment]
I can confirm the issue and will work on it in following weeks. Thanks!

**Comment by mpod** [comment]
I finally fixed it. I'm sorry for the delay.
