### ISSUE TITLE
Scrollbar always visible when menu is activated

### ISSUE THREAD

**Issue by Cydfrey** [mpod/mPage#2]
It's a small issue but...
If the navigation menu is active, the scrollbar will always be visible, even if the feeds do not take the whole page. It is visible in the screenshots from the Readme file:

![dark-theme.png](https://raw.githubusercontent.com/mpod/mPage/master/dark-theme.png)

The scrollbar shows up even if there is nothing hidden in the page.

Apart from that I really love this add-on, perfect for my use, this is why I am bothering you with this tiny thing :-)

**Comment by mpod** [comment]
It is made intentionalthat way. I just wanted to have three columns visible all the time. This means I need to set page height to be 100%, which results with visible scrollbar.

**Comment by mpod** [comment]
If you want to get rid of scrollbar, then create no-scrollbar.css file with:

#page-container {
  height: auto;
}

Go to mpage options dialog and select the file in Custom CSS parameter.
