### ISSUE TITLE
google news rss feeds dont work anymore 

### ISSUE THREAD

**Issue by daed-alus** [mpod/mPage#20]
hi there
since some time a can't use google news rss feeds anymore with mpage

all i've tested gave me an _Feed loading has failed._ error
eg https://news.google.com/news/rss

![Screenshot 2021-08-25 141557](https://user-images.githubusercontent.com/16777083/130789023-393fd9bd-c8b0-4263-aa75-26bb32130a81.jpg)

FF v91.0.2 | mPage v1.26

**Comment by mpod** [comment]
Yes, I can confirm the issue. Thanks for reporting. Google rejects the request because the request doesn't come from the same origin. Trying to find a workaround solution.

**Comment by mpod** [comment]
I've found a workaround. Navigate to: "about:config", and then change "dom.security.secFetch.enabled" to false.

Firefox 90 introduced additional headers which make problems here. More about it: https://blog.mozilla.org/security/2021/07/12/firefox-90-supports-fetch-metadata-request-headers/

I'm still searching for a more general solution.

**Comment by daed-alus** [comment]
workaround works 👍, hope u can find a real fix for this

**Comment by daed-alus** [comment]
ok that workaround is no "usable" temporary fix, cause setting _dom.security.secFetch.enabled_ to _false_ breaks some other site

**Comment by mpod** [comment]
I've found a workaround, it should be working now. Version 1.27 released.
