### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ghost** [mpod/mPage#21]
You trying to make vintage i see that, but it's killing the customize. Please! add some feature.

- Theme Customization (completely)
Choose the background color, choose the link color, choose the color that will appear after clicking the link. etc.

- Rename Title
Some sites use long names to stand out on Google. This spoils the design!

**Comment by mpod** [comment]
Theme customization hasn't happened and it looks like it won't happen at all. It is possible to tinker exported configuration file.
I added functionality for changing feed's title.
