### ISSUE TITLE
Filter by date

### ISSUE THREAD

**Issue by Agglutinator** [mpod/mPage#3]
Could you add an option to filter by discrete calender days instead of "last 24 hours" being a day? 
So that it will only show feeds from "00:00 - 23:59"
maybe seperate the options for "hours" and "day"

Also an option to show the date and time for the feeds is missing.
So that it maybe looks sth like this:
● New RSS Feed Message 1 (7.10.16 | 11:33)
● New RSS Feed Message 2 (7.10.16 | 06:52)
● New RSS Feed Message 3 (6.10.16 | 20:23)

or seperating them by day

-------------------7.10.16------------------
● New RSS Feed Message 1 (11:33)
● New RSS Feed Message 2 (06:52)
-------------------6.10.16------------------
● New RSS Feed Message 3 (20:23

Would be really grateful if you could fix/add that, then this would be the perfect rss reader!

thank you very much!

**Comment by mpod** [comment]
It makes sense. It will take me a few days to find some time for implementing this.

**Comment by mpod** [comment]
It is implemented. Check out please latest version.
