### ISSUE TITLE
questions...

### ISSUE THREAD

**Issue by atomGit** [mpod/mPage#30]
might you consider adding a global 'group by date' option? i have hundreds of feeds and configuring every one is not realistic

lastly, how does mPage fetch feeds when a domain is queried consecutively? my concern here is having a server deny repeated queries if they come too fast - for example, assume 20 feeds, all of which query youtube.com

**Comment by mpod** [comment]
Ok, request is valid, and I will work on it through next two weeks. I will also explore what happens when a site (like youtube) is repeatedly queried.

**Comment by atomGit** [comment]
if it helps, i've been using [Smart RSS](https://github.com/SmartRSS/Smart-RSS) to sub to feeds and it was found that when querying the same site consecutively, not all recent articles were returned

i think the developer addressed this by with:
* [Push throttled source at the end of queue](https://github.com/SmartRSS/Smart-RSS/commit/ffa7d3cdf6d509036a2959f07dcad15abb08a9f2) 
* [Add per-domain throttling and updating URL according to redirect](https://github.com/SmartRSS/Smart-RSS/commit/d2bd6c1636a653fe05f1e506df56696b1032c508)
* and also a thread option in the settings "Concurrent downloads"

**Comment by mpod** [comment]
After long two weeks, a new version has been released (1.34). I'm sorry for such a long delay.

**Comment by atomGit** [comment]
thanks, but i'm not seeing anything in the commit regarding the handling of a domain when the domain is [queried consecutively](https://github.com/mpod/mPage/issues/30#issuecomment-1694660109)

**Comment by mpod** [comment]
It is implemented and tested with multiple https://news.ycombinator.com/rss

Here is actual implementation:
- https://github.com/mpod/mPage/commit/6cca23d57d2296f6de795c0a5b9eb58d597bf519#diff-dfcd5582f649dba29f3cce127f34581c7b388b7a456580c48dcc23ddd1b910d0
- https://github.com/mpod/mPage/commit/6cca23d57d2296f6de795c0a5b9eb58d597bf519#diff-2e1d1b35ee93bceb8f88a9b3e61f5bf2aa28771e057a49d030ac9ce06f3e6a62

**Comment by atomGit** [comment]
ah, thank you!
