### ISSUE TITLE
Firefox Quantum support

### ISSUE THREAD

**Issue by Cydfrey** [mpod/mPage#5]
Hello,

Do you have any plans to support the new Firefox extension model?

**Comment by mpod** [comment]
Yes, I'm working on it. I use mPage as my home page in Firefox so it will be done as soon as possible. It is hard to estimate how log it will take though.

**Comment by Cydfrey** [comment]
Wonderful news!

**Comment by mpod** [comment]
First Quantum ready version is released. Probably there are some bugs to find and fix.
