### ISSUE TITLE
How to move a feed to another panel?

### ISSUE THREAD

**Issue by metbic** [mpod/mPage#6]
Hello.
Each time I add a feed to a page, the feed will show up only in the first panel. No matter if I set the panel number to 2 or to 7, I cannot move a feed to another panel.
This reduces readability. The first panel gets very very long, while the others stay completely empty.
The preset feeds however, are contributed over the panels.

FF 57 on Android Kitkat.

**Comment by mpod** [comment]
Addon is not designed for Android Firefox. Yesterday I tried it on Android for the first time, and was surprised that it is available for installation.
Anyway, I'll see in next couple of weeks what can be done here. Thanks for reporting the issue.

**Comment by mpod** [comment]
The addon is just not suitable for mobile phones.
