### ISSUE TITLE
RDF feeds creating "no feeds found" error

### ISSUE THREAD

**Issue by rbassett3** [mpod/mPage#7]
Hello,

I am a new user to mPage. I recently installed and set up the add-on, but approximately 1/3 of my feeds do not load correctly. They are scientific journal feeds, and the problematic pages use RDF. I am able to read them on my mobile device with another reader.

Here is an image of the formatting for these feeds
![image](https://user-images.githubusercontent.com/9470734/40250493-4c241eec-5a8b-11e8-97fb-53d86d7cecad.png)

and the mPage display
![image](https://user-images.githubusercontent.com/9470734/40250514-6974c424-5a8b-11e8-9681-4e349ab5a7a1.png)

**Comment by rbassett3** [comment]
I am not sure if the problem is related to the fact the feeds are RDF or that the xml files are xml 1.0. Are both of these formats supposed to be supported?

**Comment by mpod** [comment]
The thing is that from Firefox Quantum version there is no more integrated component for parsing RSS feeds, so I needed to parse them manually. Obviously, some cases are not covered with my implementation. I'll do some quick testing and release new version shortly. Thank you very much for your contribution.
